WIP:  Wechat app
koderover/zadig-portal pull request #240
Opened 2021-11-16 08:51 UTC by facethesunsea

### What this PR does / Why we need it:

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

### Check List 

- [ ] Docs have been added / updated
- [ ] Unit test / Integration test for the changes have been added
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## More information

2021-12-16 12:05 UTC, leozhang2018 requested changes

2021-12-16 12:05 UTC, leozhang2018 commented on src/components/projects/edit_pipeline/common_pipeline/pipeline.vue
> +          console.log('保存', commonInfo)
Remove console.log

2021-12-16 12:22 UTC, leozhang2018 requested changes

2021-12-16 12:22 UTC, leozhang2018 commented on src/components/projects/edit_pipeline/common_pipeline/switch_tab/basic_dialog.vue
> +    // Endpoint路径
Please use English to comment

2021-12-16 12:22 UTC, leozhang2018 commented on src/components/projects/edit_pipeline/common_pipeline/switch_tab/basic_info.vue
> +      // return Promise.resolve()
Remove it or add some comment.
For example:
  return this.$refs.basicForm.validate()
  //Todo:use promise to check in furture.
      // return Promise.resolve()

2021-12-16 12:22 UTC, leozhang2018 commented on src/components/projects/edit_pipeline/common_pipeline/switch_tab/build.vue
> +      <el-form ref="buildApp" :inline="true" :model="buildInfo" class="form-style1" label-position="top" label-width="80px">
class="form-style1" 
Please use meaningful name

2021-12-16 12:22 UTC, leozhang2018 commented on src/components/projects/pipeline/common/run_common_workflow.vue
> +          const infos = [] // 用来请求branch pr信息
Please use English.

2021-12-16 12:36 UTC, facethesunsea commented on src/components/projects/edit_pipeline/common_pipeline/switch_tab/build.vue
> +      <el-form ref="buildApp" :inline="true" :model="buildInfo" class="form-style1" label-position="top" label-width="80px">
all build use the class name, update all later I think.

2021-12-16 12:50 UTC, leozhang2018 requested changes

2021-12-16 12:50 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list.vue
> +      const res2 = await getCommonWorkflowListAPI(projectName).catch(err => {
Please use meaningful variable name.

2021-12-16 12:50 UTC, leozhang2018 commented on src/components/projects/edit_pipeline/common_pipeline/pipeline.vue
> +      <el-button type="primary" plain @click="saveCommonPipeline">保存</el-button>
CommonPipeline -> CommonWorkflow

2021-12-16 13:11 UTC, leozhang2018 requested changes

2021-12-16 13:11 UTC, leozhang2018 commented on src/store/mutations.js
> +// common pipeline
//Common Workflow

2021-12-16 13:11 UTC, leozhang2018 commented on src/utilities/validate_async.js
> +    this.validateArr = [] // []{name, valid} name唯一
Please use English

2021-12-16 13:11 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list.vue
>      deleteWorkflow (workflow) {
deleteProductWorkflow

2021-12-16 13:11 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list.vue
> +    deleteCommon (workflow) {
deleteCommonWorkflow

2021-12-16 13:11 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list.vue
> +    startCommonBuild (worflow) {
startCommonWorkflowBuild

2021-12-16 13:11 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list.vue
>      startProductBuild (workflow) {
startProductWorkflowBuild

2021-12-16 13:11 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list/common_row.vue
> +    deleteCommonPipeline (command) {
deleteCommonWorkflow

2021-12-16 13:16 UTC, leozhang2018 requested changes

2021-12-16 13:16 UTC, leozhang2018 commented on src/components/projects/edit_pipeline/common_pipeline/switch_tab/basic_dialog.vue
> +    // 请求方法
Please use English

2021-12-16 13:16 UTC, leozhang2018 commented on src/components/projects/edit_pipeline/common_pipeline/switch_tab/external.vue
> +      externalList: [
Please use empty array.

2021-12-16 13:29 UTC, leozhang2018 requested changes

2021-12-16 13:29 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list/virtual_list_item.vue
> +    <pipeline-row v-else :name="workflow.name"
ProductWorkflowRow

2021-12-16 13:29 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list/virtual_list_item.vue
> +    <CommonRow v-if="source.type === 'common'" :workflow="source"></CommonRow>
CommonWorkflowRow

2021-12-16 13:29 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list/virtual_list_item.vue
>  import pipelineRow from './pipeline_row.vue'
ProductWorkflowRow

2021-12-16 13:29 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list/virtual_list_item.vue
> +import CommonRow from './common_row.vue'
CommonWorkflowRow

2021-12-16 13:29 UTC, leozhang2018 commented on src/components/setting/integration/other.vue
> +      this.$confirm(`确定要删除这个 External 配置吗？`, '确认', {
External 配置 ->外部系统配置

2021-12-16 13:35 UTC, leozhang2018 requested changes

2021-12-16 13:35 UTC, leozhang2018 commented on src/components/projects/pipeline/common/run_common_workflow.vue
> +    getCommonPipelineInfo () {
getCommonWorkflowInfo

2021-12-16 13:35 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list.vue
>        <run-workflow
RunProductWorkflow

2021-12-16 13:35 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list.vue
>  import runWorkflow from './common/run_workflow.vue'
RunProductWorkflow

2021-12-16 13:35 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list.vue
> +    StartCommonWorkflowBuild (worflow) {
StartCommonWorkflowBuild -> startCommonWorkflowBuild

2021-12-16 13:35 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_list/common_row.vue
> +  inject: ['StartCommonWorkflowBuild', 'deleteCommonWorkflow']
startCommonWorkflowBuild -> StartCommonWorkflowBuild

2021-12-16 13:52 UTC, leozhang2018 requested changes

2021-12-16 13:52 UTC, leozhang2018 commented on src/components/projects/pipeline/common/run_common_workflow.vue
> +      <el-button :loading="loading" type="primary" plain size="small" :disabled="cantRun" @click="runCommonPipeline">启动任务</el-button>
runCommonWorkflow

2021-12-16 13:52 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_common_detail.vue
> +        this.timerId = setTimeout(this.autoRefreshHistoryTask, 3000) // just one timeout
Keep only one timer

2021-12-16 13:52 UTC, leozhang2018 commented on src/components/projects/pipeline/workflow_common_detail.vue
> +    hideAndgetCommonWorkflowTasks () {
hideAndGetCommonWorkflowTasks

2021-12-17 03:06 UTC, leozhang2018 requested changes

2021-12-17 03:06 UTC, leozhang2018 commented on src/store/index.js
> +// common workflow
Common Workflow

2021-12-17 03:06 UTC, leozhang2018 commented on src/store/index.js
> +import common_pipeline from './modules/common_pipeline'
common_workflow

2021-12-17 11:34 UTC, leozhang2018 approved these changes
LGTM

2021-12-20 02:38 UTC, merged