fix: build cache question
koderover/zadig-portal pull request #449
Opened 2022-02-08 08:02 UTC by facethesunsea

### What this PR does / Why we need it:

- fix: can't deploy if cant access cluster
- fix: prompt only once when switch storage type
- fix: hidden advanced configurations when add a cluster
- fix: add form validation

### Check List 

- [ ] Docs have been added / updated
- [ ] Unit test / Integration test for the changes have been added
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## More information

2022-02-11 01:40 UTC, fansi404 commented
Bugs have been fixed.

2022-02-16 02:03 UTC, leozhang2018 requested changes

2022-02-16 02:03 UTC, leozhang2018 commented on src/components/setting/cluster/manage.vue
> +    canConfig () {
isConfigurable

2022-02-16 02:09 UTC, merged

2022-02-16 02:10 UTC, leozhang2018 reviewed
LGTM