WIP feat: code filter
koderover/zadig-portal pull request #826
Opened 2022-05-09 02:46 UTC by liyue326

Signed-off-by: liyue326 <liyue@koderover.com>

Problem Summary:
feat: code filter

2022-05-09 12:34 UTC, fansi404 commented on src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/buildOperate.vue
> +                <span>匹配到分支：</span>
placeholder 中的内容遗漏

<img width="664" alt="image" src="https://user-images.githubusercontent.com/89375976/167410684-ad2df622-2a7b-4900-8c47-5619e8bab547.png">

2022-05-10 02:14 UTC, leozhang2018 requested changes

2022-05-10 02:14 UTC, leozhang2018 commented on config/index.js
> +const backEndAddr = 'http://dev2.8slan.com/';
Don‘t edit ths addr.

2022-05-10 11:03 UTC, leozhang2018 approved these changes
LGTM

2022-05-10 11:04 UTC, merged